// *** ROUTES ***
export const ROUTES = {
  HOME: "/",
  LOGIN: "/login",
  JOURNAL: "/journal",
  JOURNAL_CREATE: "/journal/create",
  JOURNAL_DETAIL: "/journal/detail/",
  TODO: "/todo",
  TODO_CREATE: "/todo/create",
  TODO_DETAIL: "/todo/detail/",
  SENTENCE: "/sentence",
  SENTENCE_CREATE: "/sentence/create",
  SENTENCE_DETAIL: "/sentence/detail/",
  GALLERY: "/gallery",
  STATS: "/stats",
  SETTINGS: "/settings",
  PROFILE: "/profile",
  CATEGORIES: "/categories",
  ANNIVERSARIES: "/anniversaries",
};
